<#
.SYNOPSIS
    Registers .md / .stl / .3mf to open with localViewer via "Open with > Viewer".

.DESCRIPTION
    Writes per-user HKCU classes (no admin required). Adds:
      - HKCU\Software\Classes\Applications\localViewer.cmd\shell\open\command
      - OpenWithProgids entries on the file extensions
    A small wrapper .cmd is written next to open-file.ps1 because the Windows
    "Open with" dialog does not accept .ps1 directly.

.NOTES
    Run from inside viewer/tools/. Re-run any time to refresh paths.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$toolsDir  = $PSScriptRoot
$viewerDir = Split-Path -Parent $toolsDir
$openPs1   = Join-Path $toolsDir 'open-file.ps1'
$wrapperCmd = Join-Path $toolsDir 'open-file.cmd'

if (-not (Test-Path -LiteralPath $openPs1)) {
    Write-Error "open-file.ps1 not found at $openPs1"
    exit 1
}

# ---- write wrapper .cmd (so Explorer's "Open with" can target it) ----
$cmdContent = @"
@echo off
rem localViewer launcher (auto-generated by register-windows.ps1)
powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$openPs1" "%~1"
"@
Set-Content -LiteralPath $wrapperCmd -Value $cmdContent -Encoding ASCII
Write-Host "Wrote launcher: $wrapperCmd"

# ---- register an Application entry under HKCU\Software\Classes ----
$appKey      = 'HKCU:\Software\Classes\Applications\localViewer.cmd'
$shellOpen   = "$appKey\shell\open\command"
$friendly    = "$appKey"

New-Item -Path $shellOpen -Force | Out-Null
Set-ItemProperty -Path $shellOpen -Name '(default)' -Value "`"$wrapperCmd`" `"%1`""
Set-ItemProperty -Path $friendly  -Name 'FriendlyAppName' -Value 'localViewer'
# SupportedTypes — extensions Explorer will offer this app for
$supportedTypes = "$appKey\SupportedTypes"
New-Item -Path $supportedTypes -Force | Out-Null
Set-ItemProperty -Path $supportedTypes -Name '.md'   -Value ''
Set-ItemProperty -Path $supportedTypes -Name '.stl'  -Value ''
Set-ItemProperty -Path $supportedTypes -Name '.3mf'  -Value ''

# ---- add to OpenWithList for each extension ----
foreach ($ext in @('.md', '.stl', '.3mf')) {
    $owp = "HKCU:\Software\Classes\$ext\OpenWithProgids"
    New-Item -Path $owp -Force | Out-Null
    Set-ItemProperty -Path $owp -Name 'Applications\localViewer.cmd' -Value ''
    $owl = "HKCU:\Software\Classes\$ext\OpenWithList\localViewer.cmd"
    New-Item -Path $owl -Force | Out-Null
}

Write-Host ""
Write-Host "Registered localViewer for: .md  .stl  .3mf" -ForegroundColor Green
Write-Host "Right-click a file -> Open with -> localViewer."
Write-Host "To set as default: Open with -> Choose another app -> localViewer -> Always."
Write-Host ""
Write-Host "Uninstall with: unregister-windows.ps1"
